### ISSUE TITLE
兼容toolbar问题

### ISSUE THREAD

**Issue by diorslau** [Zackratos/UltimateBar#1]
请问加了toolbar的话 怎么适配呢  按照你文档说的 设置全透明的话   toolbar就被定上去了

**Comment by Zackratos** [comment]
确实会有你说的问题，你需要在根布局中添加 android:fitsSystemWindows="true"

**Comment by diorslau** [comment]
这个我知道  但是这样要去设置 跟布局的背景跟toolbar一致, 并不是真正意义的toolbar沉侵 , toolbar是透明的  和banner图重叠一起在顶部, 如果这样 那banner图也无法延伸到顶部实现沉侵了

**Comment by Zackratos** [comment]
我不太清除你想表达的意思，不知道你到底想要什么样的效果，你可以看看我有一个项目叫 "PureMusic"，那里面就是用了透明的 toolbar，并且背景图延伸到顶部了，但是 toolbar 没有延伸到顶部，不知道是不是你想要的效果

**Comment by Zackratos** [comment]
那个项目里面有截图，你可以看看是不是你要的效果

**Comment by zouxianbincc** [comment]
@Zackratos 他的意思是仿iOS 的效果 。 标题栏是模糊的半透明，当ListVIew 等 滑动控件，往上滑动时，在标题栏上能模糊看到ListView 的内容

**Comment by Zackratos** [comment]
@diorslau 我明白了，你需要先设置沉浸状态栏，然后在 toolbar 的上面加一个高度为状态栏高度的 View 就可以了
