### ISSUE TITLE
使用沉浸式导航栏的时候底部虚拟按键挡住了布局

### ISSUE THREAD

**Issue by Power-Android** [Zackratos/UltimateBar#10]
如题，在加入fitsSystemWindows=true以后，沉浸式导航栏又失效。

**Comment by Zackratos** [comment]
@Power-Android  沉浸式导航栏要的就是挡住布局的效果啊，你仔细看看我的 demo 里的沉浸式导航栏的效果图，是不是布局把那个图片给挡住了，只不过导航栏是透明的而已
