### ISSUE TITLE
如何只隐藏导航而不隐藏状态栏

### ISSUE THREAD

**Issue by wxjer** [Zackratos/UltimateBar#17]
现在耦合在一起

**Comment by Zackratos** [comment]
现在确实是耦合在一起，我不确定能不能只隐藏导航栏而不隐藏状态栏，下个版本试一下能不能实现

**Comment by Zackratos** [comment]
大兄弟，不知道你会不会看到这条回复，多年之后，我终于彻底解决了耦合在一起的问题，欢迎使用我的新库 [UltimateBarX](https://github.com/Zackratos/UltimateBarX)
@wxjer
