### ISSUE TITLE
android:Theme.Holo 主题下不能设置导航栏全透明

### ISSUE THREAD

**Issue by NotMyYida** [Zackratos/UltimateBar#18]
楼主还在维护吗？我有个应用使用了 android:Theme.Holo 的主题，用了楼主的库，设置导航栏全透明，但效果是半透明的。折腾了挺久，也不能使 android:Theme.Holo 主题的Activity为全透明导航栏。楼主可以给个建议吗？

**Comment by Zackratos** [comment]
@NotMyYida 中间停了很久，最近又重新维护了，Holo 主题我没用过，不知道效果是什么样的，建议用 AppCompat 主题，这几天重构了代码，现在功能更强大了，欢迎使用

**Comment by NotMyYida** [comment]
多谢楼主，我做的是一个防小米Camera的相机，需要把导航栏透明，尝试了很久也没弄好，只能弄成半透明的，后来抖了个机灵，把导航栏上方的颜色也设置为半透明颜色就把问题解决了。

**Comment by Zackratos** [comment]
这个库已经不再维护了，最近我有新开发了一个库 [UltimateBarX](https://github.com/Zackratos/UltimateBarX)，功能更强大，欢迎尝试体验
@NotMyYida
