### ISSUE TITLE
Set background and foreground color of status bar and navigation bar when make them hidden

### ISSUE THREAD

**Issue by AndiosDev2013** [Zackratos/UltimateBar#21]
Hi, Thanks for your great library.

I have one trouble when use your library.
I want to hide the status bar and navigation bar at first.(works great now)
Second, The app user can expand them by dragging from the edge of screen, at this time, I want to make the status bar and navigation bar which have transparent background and transparent foreground, so that I can make the user do not realize the status bar and navigation bar even though it expanded.

I used your code for hiding status bar and navigation bar.
But It did not have transparent background(have grey transparent background and white foreground) and I could not change them.
I was testing using Android 8.0.1/tablet(landscape)

Hope to get your kind reply.
Thanks.

**Comment by Zackratos** [comment]
I'm sorry for my late reply, thank you for your feedback, but I no longer maintain this library. Recently I have developed a new library with more powerful functions that should solve your problem.  [UltimateBarX](https://github.com/Zackratos/UltimateBarX) Try it out
@AndiosDev2013
