### ISSUE TITLE
布局设置背景时出现的一个小问题

### ISSUE THREAD

**Issue by chenyacheng** [Zackratos/UltimateBar#23]
![_20190211164844](https://user-images.githubusercontent.com/29671005/52553029-3e8f0380-2e1d-11e9-91c4-b382df874873.png)
![_20190211164908](https://user-images.githubusercontent.com/29671005/52553037-4353b780-2e1d-11e9-9a3c-3d23e5e73ad5.png)
这个怎么弄呀

**Comment by Zackratos** [comment]
什么问题

**Comment by xucoolmeng** [comment]
界面根布局设置背景后 状态栏设置的颜色 失效   我也遇到了这个问题

**Comment by glmxzz** [comment]
+1 ，有没有解决方法？

**Comment by xucoolmeng** [comment]
根布局，再套一层




------------------ 原始邮件 ------------------
发件人: "glmxzz"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 上午9:56
收件人: "Zackratos/UltimateBar"<UltimateBar@noreply.github.com>;
抄送: "徐猛"<649823069@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Zackratos/UltimateBar] 布局设置背景时出现的一个小问题 (#23)




+1 ，有没有解决方法？

**Comment by chenyacheng** [comment]
> +1，有没有解决方法？

设置成白色
![image](https://user-images.githubusercontent.com/29671005/62842141-71d62080-bce2-11e9-87ef-564933dd24cf.png)
![image](https://user-images.githubusercontent.com/29671005/62842148-7ef30f80-bce2-11e9-8812-b33796195182.png)
根布局不要设置背景颜色，在代码里设置

**Comment by Like151320** [comment]
根布局设置颜色后状态栏颜色会失效，因为状态栏是被直接塞到DecorView的，是在根布局的下层，所以被根布局遮挡住了。
我是在根布局的顶部加入一个24dp的View，只做状态栏的背景使用，根据版本判断显隐。

**Comment by Zackratos** [comment]
这个库已经不再维护了，最近我有新开发了一个库[UltimateBarX](https://github.com/Zackratos/UltimateBarX)，应该可以解决这个问题，欢迎尝试体验
@yacheng199306 @glmxzz @xucoolmeng @Like151320
