### ISSUE TITLE
6.0以下如何设置字体和图标为灰色?设置statusDark无效

### ISSUE THREAD

**Issue by EmKs** [Zackratos/UltimateBar#24]
我在BaseActivity中统一使用
`UltimateBar.Companion.with(this)
                .statusDrawable(drawableBar)   // Android 6.0 以下状态栏灰色模式时状态栏颜色
                .statusDrawable2(drawableBar)
                .statusDark(true)    // 状态栏灰色模式(Android 6.0+)，默认 flase
                .applyNavigation(true)     // 应用到导航栏，默认 flase
                .navigationDrawable(drawableBar)       // Android 8.0 以下导航栏灰色模式时导航栏颜色
                .navigationDrawable2(drawableBar)
                .navigationDark(true)       // 导航栏灰色模式(Android 8.0+)，默认 false
                .create()
                .drawableBar();`

DrawableBar 为白色背景，在6.0以下如何将图标和字体变为灰色，否则看不见啊，6.0以上则没这个问题，

**Comment by Zackratos** [comment]
因为原生的 Android 6.0 以下是无法设置状态栏字体颜色的，所以加了一个 statusDrawable2 方法，这个方法就是在 Android 6.0 以下的时候，重新设置状态栏背景色的，防止你说的看不见问题
