### ISSUE TITLE
修改状态栏时，导航栏变成了黑色

### ISSUE THREAD

**Issue by Like151320** [Zackratos/UltimateBar#29]
在一个有导航和状态栏的手机上，需求是将状态栏的文字设为黑色，但当我调用工具让文字变黑后
UltimateBar.Companion.with(getActivity())
                    .statusDark(true)// 状态栏灰色模式(Android 6.0+)，默认 flase
                    .create()
                    .transparentBar();
发现导航栏的背景变黑了，我查找后发现核心方法 setBar 对导航栏的默认处理是 window.navigationBarColor = Color.BLACK。
现在只能重写这个类来解决了。
小米9会自动根据背景色决定导航栏的颜色，所以就出现了这个问题。

这个工具很好用，建议当使用者不调用导航栏方法时，不对导航栏做任何处理。

**Comment by Zackratos** [comment]
现在确实有这样的问题，主要是因为这个库当时设计的不好，最近我又新开发了一个库，[UltimateBarX](https://github.com/Zackratos/UltimateBarX)，欢迎尝试体验，另外你说的这个问题在新版本的库应该也存在，主要是因为默认导航栏是黑色，但是非常好解决，你可以单独设置状态栏和导航栏，功能更强大，有什么问题欢迎再跟我交流
@Like151320
