### ISSUE TITLE
能不能增加单独分别设置状态栏或者导航栏的功能

### ISSUE THREAD

**Issue by ArcherYL** [Zackratos/UltimateBar#3]
比如有些应用首页顶部因为有广告banner 状态栏需要全透明，但是导航栏不需要，您的这个好像只能一起配置

**Comment by Yunme** [comment]
+1 我也需要这种需求，哈哈。

**Comment by Yunme** [comment]
我提了一个 request ，新加了一个 type 就可以 单独设置了，你有兴趣可以看一下我的 fork .

**Comment by Zackratos** [comment]
我最近在找工作，有点忙，等我新工作安定下来之后更新一个版本，增加这个功能，顺便看看 @Yunme 的 request

**Comment by Yunme** [comment]
我的实现方式很简单，你有空看一下，怎么实现起来更优雅一些。

**Comment by ArcherYL** [comment]
嗯嗯，好的

**Comment by Zackratos** [comment]
新版本已经增加了单独设置状态栏和导航栏的方法

**Comment by ArcherYL** [comment]
赞
