### ISSUE TITLE
applyNavigation(false)无效，虚拟按钮与布局重叠

### ISSUE THREAD

**Issue by mudcastles** [Zackratos/UltimateBar#30]
我想实现的效果是沉浸状态栏，不应用到导航栏，让布局在虚拟按键上方显示。我使用
`        UltimateBar.Companion.with(this)
            .applyNavigation(false)         // 是否应用到导航栏
            .create()
            .immersionBar()
`
运行后虚拟按键挡住了布局。

**Comment by Zackratos** [comment]
这个库不再维护了，试试我的最新的库 [UltimateBarX](https://github.com/Zackratos/UltimateBarX) 吧，应该可以解决你的问题，如果有问题，欢迎在提 issues @mudcastles
