### ISSUE TITLE
华为mate30 pro状态栏显示重叠

### ISSUE THREAD

**Issue by limhGeek** [Zackratos/UltimateBar#31]
![image](https://user-images.githubusercontent.com/29226199/71303873-85fcfd80-23f9-11ea-9886-c92e85ec4074.png)

**Comment by Zackratos** [comment]
试试我的最新的库 [UltimateBarX](https://github.com/Zackratos/UltimateBarX)，如果有问题，欢迎在提 issues @limhGeek
