### ISSUE TITLE
对于含有DrawaLayout的问题

### ISSUE THREAD

**Issue by cctvjavascript** [Zackratos/UltimateBar#6]
对于含有DrawaLayout的 为什么DecorView添加状态栏和导航栏的时候要addView(View,index)

**Comment by Zackratos** [comment]
@cctvjavascript 因为主布局必须是自定义颜色的状态栏和导航栏，相当于 setColorBar 方法

**Comment by cctvjavascript** [comment]
我想问的是为啥是addView(状态栏,0)和addView(导航View，1)而不是addView(导航栏）和addView(状态栏View）；DecorView本身就是FrameLayout的一个子类，而你在创建状态栏和导航栏的时候有给他们设置FrameLayout.Paramter的Gravity属性；所以addView(状态栏)和addView(状态栏，0）应该是相同的才对呀？

**Comment by Zackratos** [comment]
@cctvjavascript 但是抽屉也是添加到 DecorView 上面的，如果直接 addView(状态栏) 就会出现一个问题，就是添加的状态栏会把抽屉也覆盖住，而我需要的效果是不覆盖抽屉的状态栏和导航栏
