### ISSUE TITLE
fragment的沉浸式

### ISSUE THREAD

**Issue by Fish-Bin** [Zackratos/UltimateBar#7]
这个工具类好像不支持fragment里图片沉浸式

**Comment by Zackratos** [comment]
为什么要支持 fragment 沉浸，fragment 不是在 activity 内部的吗，让 activity 沉浸就好了啊

**Comment by Fish-Bin** [comment]
@Zackratos 我不同fragment要求不同的状态栏颜色，其中有一个是要求图片沉浸式，

**Comment by Zackratos** [comment]
@rainbowBin 切换 fragment 的时候重新调整状态了颜色和沉浸式效果就好了

**Comment by Zackratos** [comment]
@rainbowBin 或者在 Activity 中把状态栏设置成沉浸式的效果，然后你在每个 Fragment 中需要的效果就可以直接通过 Fragment 来设置了
